### ISSUE TITLE
Keyframes are not applied to sequences in background and "Lock interface" modes

### ISSUE THREAD

**Issue by w1th0utnam3** [InteractiveComputerGraphics/blender-sequence-loader#10]

**Comment by losanc** [comment]
hi,
have you tried with latest version, I think @digitalillusions  have fixed this

**Comment by w1th0utnam3** [comment]
Yes, I downloaded the latest GitHub release. The sequence itself plays fine even in locked mode. But if you add something with keyframes on the sequence (e.g. rotate the sequence around an axis), the keyframed properties are only updated in unlocked GUI mode rendering. With locked interface it's stuck on the keyframe that was shown last in the GUI.
